---
title: "Éphésiens 2: nous étions sauvé·es par grâce"
book: "Ephesians"
chapter: "2"
theme: "salut, amour divine, unité"
lang: fr
---

[texte biblique: Éphésiens 2 ](https://lire.la-bible.net/bible/LSG/EPH.2)

## Versets clés

> 1Vous étiez morts par vos offenses et par vos péchés, 2dans lesquels vous marchiez autrefois, selon le train de ce monde, selon le prince de la puissance de l’air, de l’esprit qui agit maintenant dans les fils de la rébellion. 3Nous tous aussi, nous étions de leur nombre, et nous vivions autrefois selon les convoitises de notre chair, accomplissant les volontés de la chair et de nos pensées, et nous étions par nature des enfants de colère, comme les autres… 4Mais Dieu, qui est riche en miséricorde, à cause du grand amour dont il nous a aimés, 5nous qui étions morts par nos offenses, nous a rendus à la vie avec Christ (c’est par grâce que vous êtes sauvés);

> 8Car c’est par la grâce que vous êtes sauvés, par le moyen de la foi. Et cela ne vient pas de vous, c’est le don de Dieu. 9Ce n’est point par les œuvres, afin que personne ne se glorifie. 10Car nous sommes son ouvrage, ayant été créés en Jésus-Christ pour de bonnes œuvres, que Dieu a préparées d’avance, afin que nous les pratiquions.

> 19Ainsi donc, vous n’êtes plus des étrangers, ni des gens du dehors; mais vous êtes concitoyens des saints, gens de la maison de Dieu. 20Vous avez été édifiés sur le fondement des apôtres et des prophètes, Jésus-Christ lui-même étant la pierre angulaire. 21En lui tout l’édifice, bien coordonné, s’élève pour être un temple saint dans le Seigneur. 22En lui vous êtes aussi édifiés pour être une habitation de Dieu en Esprit.

## Questions pour la réflexion

- Comment comprends-tu la déclaration que tu étais «mort·e » par tes « offenses » et tes « péchés » ?
  - Penses-tu d'avoir reçu la vie nouvelle avec Christ ?
- Si une personne est sauvée par « la grâce », et « n'est point par les œuvres », est-il toujours important de pratiquer sa foi dans les œuvres ? 
- D'être  « concitoyen·nes des saint·es » semble à quoi concrètement pour toi ?
