---
title: "Jacques 1: Le bonheur de persévérer dans la foi
book: James
chapter: 1
theme: "persévérance, épreuve, péché"
lang: fr
---

[texte biblique: Jacques 1](https://lire.la-bible.net/bible/LSG/JAS.1)

## Versets clés

> 3... l’épreuve de votre foi produit la patience.

> 13Que personne, lorsqu’il est tenté, ne dise: C’est Dieu qui me tente. Car Dieu ne peut être tenté par le mal, et il ne tente lui-même personne. 14Mais chacun est tenté quand il est attiré et amorcé par sa propre convoitise. 15Puis la convoitise, lorsqu’elle a conçu, enfante le péché...

>  19...Ainsi, que toute personnes soient prompte à écouter, lente à parler, lente à se mettre en colère; 20car la colère des personnes n’accomplit pas la justice de Dieu.

> 22Mettez en pratique la parole, et ne vous bornez pas à l’écouter, en vous trompant vous-mêmes par de faux raisonnements.

> 23...si quelqu’un écoute la parole et ne la met pas en pratique, il est semblable à un homme qui regarde dans un miroir son visage naturel, 24et qui, après s’être regardé, s’en va, et oublie aussitôt quel il était.

## Questions pour la réflexion

- Y a-t-il des occasions dans ta vie que tu sentis une épreuve de ta foi ?
  - Blâme-tu Dieu pour ces épreuves ?
  - Sens-tu avoir gagné de « la patience » à travers de cettes expériences ?
- Selon Jacques 1, quelle est la source des mauvaises tentations ? Est-tu d'accord ?
- Comment comprend-tu
  - « car la colère des personnes n'accomplit pas la justice de Dieu » (1:19)?
  - le « faux raisonnement » mentionné en verset 22 ?
