---
title: "Jérémie 1: les portraits bibliques de Dieu"
book: "Jeremiah"
chapter: "1"
theme: "justice divine, prophète, portrait biblique de Dieu"
lang: fr
---

[texte biblique: Jérémie 1](https://lire.la-bible.net/bible/LSG/JER.1)

## Versets clés

> 4La parole de l’Éternel me fut adressée, en ces mots: 5Avant que je t’eusse formé dans le ventre de ta mère, je te connaissais, et avant que tu fusses sorti de son sein, je t’avais consacré, je t’avais établi prophète des nations.

> 9Puis l’Éternel étendit sa main, et toucha ma bouche; et l’Éternel me dit: Voici, je mets mes paroles dans ta bouche. 10Regarde, je t’établis aujourd’hui sur les nations et sur les royaumes, pour que tu arraches et que tu abattes, pour que tu ruines et que tu détruises, pour que tu bâtisses et que tu plantes.

## Questions pour la réflexion

- En Jérémie 1, Jérémie se déclarait lui-même prophète. En effet, beaucoup des personnes se déclaraient prophètes à l'époque. Est-ce que Jérémie différent des autres ? Pourquoi ?

- Comment le portrait de Dieu dans Jérémie 1 s’inscrit‑il dans un ensemble plus large de portraits bibliques de Dieu ?

