---
title: "Jean 20: Heureux ceux qui n'ont pas vu, et qui ont cru"
book: John
chapter: 20
theme: "croyance, résurrection, incrédulité"
lang: fr
---

[texte biblique: Jean 20](https://lire.la-bible.net/bible/LSG/JHN.20)

## versets clés

> 24Thomas, appelé Didyme, l’un des douze, n’était pas avec eux lorsque Jésus vint. 25Les autres disciples lui dirent donc: Nous avons vu le Seigneur. Mais il leur dit: Si je ne vois dans ses mains la marque des clous, et si je ne mets mon doigt dans la marque des clous, et si je ne mets ma main dans son côté, je ne croirai point. 

> 27Puis il dit à Thomas: Avance ici ton doigt, et regarde mes mains; avance aussi ta main, et mets-la dans mon côté; et ne sois pas incrédule, mais crois. 28Thomas lui répondit: Mon Seigneur et mon Dieu! Jésus lui dit:
> 
> 29Parce que tu m’as vu, tu as cru. Heureux ceux qui n’ont pas vu, et qui ont cru!

## questions pour la réflexion

- Pense-tu que Thomas a été raisonnable alors qu'il a insisté qu'il « ne croira point » sauf s'il voit Jésus réssucité avec ses propres yeux ?
- Pourquoi Jésus a dit « Heureux ceux qui n'ont pas vu, et qui ont cru ? » (20:29)
 
