---
title: "Jean 10: le bon berger et ses brebis"
book: John
chapter: 10
theme: "bon berger, brebis, confiance"
lang: fr
---

[texte biblique: Jean 10](https://lire.la-bible.net/bible/LSG/JHN.10)

## Versets clés

> 11Je suis le bon berger. Le bon berger donne sa vie pour ses brebis. 12Mais le mercenaire, qui n’est pas le berger, et à qui n’appartiennent pas les brebis, voit venir le loup, abandonne les brebis, et prend la fuite; et le loup les ravit et les disperse. 13Le mercenaire s’enfuit, parce qu’il est mercenaire, et qu’il ne se met point en peine des brebis. Je suis le bon berger. 14Je connais mes brebis, et elles me connaissent, 15comme le Père me connaît et comme je connais le Père; et je donne ma vie pour mes brebis. 16J’ai encore d’autres brebis, qui ne sont pas de cette bergerie; celles-là, il faut que je les amène; elles entendront ma voix, et il y aura un seul troupeau, un seul berger. 17Le Père m’aime, parce que je donne ma vie, afin de la reprendre. 18Personne ne me l’ôte, mais je la donne de moi-même; j’ai le pouvoir de la donner, et j’ai le pouvoir de la reprendre: tel est l’ordre que j’ai reçu de mon Père. 19Il y eut de nouveau, à cause de ces paroles, division parmi les Juifs. 20Plusieurs d’entre eux disaient: Il a un démon, il est fou; pourquoi l’écoutez-vous? 21D’autres disaient: Ce ne sont pas les paroles d’un démoniaque; un démon peut-il ouvrir les yeux des aveugles?

> 22On célébrait à Jérusalem la fête de la Dédicace. C’était l’hiver. 23Et Jésus se promenait dans le temple, sous le portique de Salomon. 24Les Juifs l’entourèrent, et lui dirent: Jusques à quand tiendras-tu notre esprit en suspens? Si tu es le Christ, dis-le nous franchement. 25Jésus leur répondit: Je vous l’ai dit, et vous ne croyez pas. Les œuvres que je fais au nom de mon Père rendent témoignage de moi.

## Questions pour la réflexion

- Selon toi, pourquoi les Juifs ont été divisé pour Jésus ?
- Qui sont les « brebis » ici ?
