---
title: "Luc 6: désamorcer la violence"
book: Luke
chapter: 6
theme: "compassion, réciprocité, fraternité, non‑vengeance, charité patiente"
lang: fr
---

[texte biblique: Luc 6](https://lire.la-bible.net/bible/LSG/LUK.6)

## Versets clés

> 31Ce que vous voulez que les autres fassent pour vous, faites-le de même pour eux. 

> 29Si quelqu’un te frappe sur une joue, présente-lui aussi l’autre. 

> 37Ne jugez point, et vous ne serez point jugés; ne condamnez point, et vous ne serez point condamnés; absolvez, et vous serez absous. 38Donnez, et il vous sera donné.

> 39...Un aveugle peut-il conduire un aveugle? Ne tomberont-ils pas tous deux dans une fosse?

> 42...comment peux-tu dire à ton frère: Frère, laisse-moi ôter la paille qui est dans ton œil, toi qui ne vois pas la poutre qui est dans le tien? Hypocrite, ôte premièrement la poutre de ton œil, et alors tu verras comment ôter la paille qui est dans l’œil de ton frère.

> 44...chaque arbre se connaît à son fruit. 

## Questions pour la réflexion

- Verset 31 est fréquemment comparé avec un proverbe chinois: « Ce qui on ne veut pas il ne faut pas donner aux autres. » Pour toi, expresse-t-elles les deux expressions le même sens ? Pourquoi ?

- Comment tu interprète verset 29 ? Donnes-tu littéralement l'autre joue si on te frappe sur une joue ?

- Lisant verset 42, réfléchis sur tes propres expériences : As-tu jamais eu « la poutre » dans ton œil ? As-tu été conscient·e de l'existence de la poutre ? As-tu essayé de « ôter la paille dans l'œil d'un autre personne à l'époque ?

- Comment comprends-tu que « chaque arbre se connaît à son fruit » ? Est-tu d'accord ?
