---
title: "Matthieu 18: pardonner de tout ton cœur"
book: "Matthiew"
chapter: "18"
theme: "humilité, fraternité, péché, réconciliation, pardon"
lang: fr
---

[texte biblique: Matthieu 18](https://lire.la-bible.net/bible/LSG/MAT.18)

## Versets clés

> 4...quiconque se rendra humble comme ce petit enfant sera le plus grand dans le royaume des cieux. 

> 20...là où deux ou trois sont assemblés en mon nom, je suis au milieu d’eux.

> 15Si ton frère a péché, va et reprends-le entre toi et lui seul. S’il t’écoute, tu as gagné ton frère. 16Mais, s’il ne t’écoute pas, prends avec toi une ou deux personnes, afin que toute l’affaire se règle sur la déclaration de deux ou de trois témoins. 17S’il refuse de les écouter, dis-le à l’Église; et s’il refuse aussi d’écouter à l’Église, qu’il aie une autre foi pour toi.

> 23C’est pourquoi, le royaume des cieux est semblable à un roi qui voulut faire rendre compte à ses serviteurs. 24Quand il se mit à compter, on lui en amena un qui devait dix mille talents. 25Comme il n’avait pas de quoi payer, son maître ordonna qu’il fût vendu, lui, sa femme, ses enfants, et tout ce qu’il avait, et que la dette fût acquittée. 26Le serviteur, se jetant à terre, se prosterna devant lui, et dit: Seigneur, aie patience envers moi, et je te paierai tout. 27Ému de compassion, le maître de ce serviteur le laissa aller, et lui remit la dette. 28Après qu’il fut sorti, ce serviteur rencontra un de ses compagnons qui lui devait cent deniers. Il le saisit et l’étranglait, en disant: Paie ce que tu me dois. 29Son compagnon, se jetant à terre, le suppliait, disant: Aie patience envers moi, et je te paierai. 30Mais l’autre ne voulut pas, et il alla le jeter en prison, jusqu’à ce qu’il eût payé ce qu’il devait. 31Ses compagnons, ayant vu ce qui était arrivé, furent profondément attristés, et ils allèrent raconter à leur maître tout ce qui s’était passé. 32Alors le maître fit appeler ce serviteur, et lui dit: Méchant serviteur, je t’avais remis en entier ta dette, parce que tu m’en avais supplié; 33ne devais-tu pas aussi avoir pitié de ton compagnon, comme j’ai eu pitié de toi? 34Et son maître, irrité, le livra aux bourreaux, jusqu’à ce qu’il eût payé tout ce qu’il devait. 35C’est ainsi que mon Père céleste vous traitera, si chacun de vous ne pardonne à son frère de tout son cœur.

## Questions pour la réflexion

- Pour toi, être « humble » (MAT 18:4) veut dire quoi ?
- Comment comprends-tu
  - les instructions données par Jésus sur un frère ayant péché (MAT 18:15-17) ?
  - « là où deux ou trois sont assemblés en mon nom, je suis au milieu d'eux » (MAT 18:20) ?
  - la parabole du serviteur qui doit au roi dix mille talents (MAT 18:23-35) ?
