project:
  type: website

website:
  title: "Bible & Taizé"
  description: "Chants, programmes et méditations bibliques de Taizé"
  search: true
  navbar:
    right:
      - icon: house-fill
        href: https://ron-ronzz-org.github.io/rondemy/
        text: "rondemy home"
  sidebar:
    style: "docked"
    contents:
      - section: "Méditations bibliques"
        contents:
          - chapters/programmes.qmd
          - section: "Juillet 2026"
            contents:
              - chapters/jas-2-fr.qmd
              - chapters/psa-34-fr.qmd
              - chapters/jhn-20-fr.qmd
              - chapters/jhn-10-fr.qmd
              - chapters/jas-1-fr.qmd
              - chapters/mat-11-fr.qmd
              - chapters/luk-6-fr.qmd
              - chapters/sir-7-fr.qmd
              - chapters/mat-18-fr.qmd
              - chapters/eph-2-fr.qmd
              - chapters/jer-1-fr.qmd
              - chapters/mat-13-fr.qmd

      - section: "Chants"
        contents:
          - chapters/chants.qmd

format:
  html:
    theme: cosmo
    toc: true
