project:
  type: website

website:
  title: "Computer Programming with AI"
  description: "Programming in the era of AI with help from LLM"
  search: true
  navbar:
    right:
      - icon: house-fill
        href: https://rondemy.ronzz.org/
        text: "rondemy home"
  sidebar:
    style: "docked"
    contents:
      - section: "Introduction to artificial intelligence"
        contents:
          - chapters/defining-ai.qmd
          - chapters/ANN.qmd

format:
  html:
    theme: cosmo
    toc: true
